### PR TITLE
release/3.0.13

### PR DESCRIPTION
**Pull request by mayurngondhkar**
Changes

1. [SRM-978] Reroll patch for `yaml_content`
2. [fix: 🐛 use dark theme header, set accordions to rich_text (](https://github.com/dpc-sdp/tide_demo_content/pull/66/commits/32f704bc958be0f72acd442fddb227fcc4cff289)https://github.com/dpc-sdp/tide_demo_content/pull/53[)](https://github.com/dpc-sdp/tide_demo_content/pull/66/commits/32f704bc958be0f72acd442fddb227fcc4cff289)

[SRM-978]: https://digital-vic.atlassian.net/browse/SRM-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mayurngondhkar** [comment]
Have to fix up the build and build suggest tests failing

**Comment by MdNadimHossain** [comment]
ci build failed

**Review by anthony-malkoun — CHANGES_REQUESTED** [review]
Re-rolled patch not applying?

**Comment by MdNadimHossain** [comment]
They did a release recently, which broke the 2nd patch as well. I have re-rolled the 2nd patch and updated the merge request. The build should pass now
@mayurngondhkar

**Comment by mayurngondhkar** [comment]
You beat me to it @MdNadimHossain by 6 mins. I had the rerolled patch ready.

**Review by MdNadimHossain — APPROVED** [review]

**Pull request merged**
